spring:
  application:
    name: base_spring_boot

  datasource:
    url: jdbc:mysql://localhost:3306/base_core?createDatabaseIfNotExist=true&useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=Asia/Ho_Chi_Minh
    username: root
    password: 123456
    driver-class-name: com.mysql.cj.jdbc.Driver

  jackson:
    time-zone: Asia/Ho_Chi_Minh

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true

  mail:
    host: smtp.gmail.com
    port: 587
    username: hgphuchgce181933@gmail.com
    password: tqtxxohacfxsrlqi
    properties:
      mail.smtp.auth: true
      mail.smtp.starttls.enable: true

  servlet:
    multipart:
      max-file-size: 200MB
      max-request-size: 200MB

payos:
  client-id: e767d7c2-2e6d-4918-9196-a7bf65da19dc
  api-key: 1004d503-d154-4ea1-8bdc-348c6de2a0ed
  checksum-key: 419a6b86e134f3959ce79bdf30022ca8cb48a055fcaaf05950b97a282c0c7442
  base-url: https://api-merchant.payos.vn
  return-url: http://localhost:5173/wallet/success
  cancel-url: http://localhost:5173/wallet/cancel

jwt:
  secret:
    key: Ascmkkqdnmsdfrtgsyuhidj21ue120938219321ndsad
  expired:
    access: 604800

open:
  api:
    title: Base Spring Boot API (DEV)
    version: 1.0.0
    serverUrl: http://localhost:8080
gemini:
  api:
    key: AIzaSyDDGhsWqlFUx3-Y-mgBV-odx7lit1--baQ